---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  # namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # image: docko/datawire/backend:0.4.1
          image: katvik001/openai-frontend
          ports:
            - name: http
              containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  # namespace: backend
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    app: backend