---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  # namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          # image: docker.io/datawire/frontend:0.4.1
          image: katvik001/openai-backend:1
          ports:
            - name: http
              containerPort: 5173
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi


---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  # namespace: backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5173
  selector:
    app: frontend
